### ISSUE TITLE
Is this useable for inputs?

### ISSUE THREAD

**Issue by Bastler100** [maarten-pennings/howto#6]
Hello,
is the library also useable for fast inputs? Can you show an example?
Many thanks 
Hans

**Comment by maarten-pennings** [comment]
Hi Hans, Which library? This how-to has 10ish topics, which are you referring to?

**Comment by Bastler100** [comment]
I mean the "gpio_struct.h" . You show the way for fast outputs? Is there a way or example for fast inputs?

**Comment by Bastler100** [comment]
ESP32-fast-gpio

**Comment by maarten-pennings** [comment]
I had to try it out myself, but yes it is.
I added a small demo, see the [howto](https://github.com/maarten-pennings/howto/blob/main/esp32-fast-gpio/esp32-fast-gpio.md#input).

If you're happy, feel free to close the issue.

**Comment by Bastler100** [comment]
Hello,
many thanks for your fast answer. I see the "gpio_struct.h" not in the ESP_C3 Branch. Does it also work with the ESP32_C3?
I find these libraries not in the Arduino Library Manager. In what kind of way its possible to install these libraries in the
Arduino Ide?
Thanks for your efforts
Hans

**Comment by maarten-pennings** [comment]
Hi Hans,

I don't have a ESP32C3 here at home.
When I look in the files that come with the ESP32 board installation in Arduino, I see this tree

```
C:\Users\maarten\AppData\Local\Arduino15\packages\esp32\tools\esp32-arduino-libs\idf-release_v5.1-bd2b9390ef
```

It has these subdirectories (one per core)

```
esp32
esp32c3
esp32c6
esp32h2
esp32s2
esp32s3
```

and when I go into the `esp32c3` I find

```
C:\Users\maarten\AppData\Local\Arduino15\packages\esp32\tools\esp32-arduino-libs\idf-release_v5.1-bd2b9390ef\esp32c3\include\soc\esp32c3\include\soc\gpio_struct.h
```

So the file `gpio_struct.h` comes from the **Arduino Board Manager**, not the **Arduino Library Manager**. 

So I would say you should have the file, and my sketch should compile for you, provided you select the correct board (in the drop down in Arduino's green button bar). Good luck (I'm OoO for one week now).

Maarten

**Comment by Bastler100** [comment]
Hello Maarten,
i make some tests with the GPIO_struct.h .The output works, but with the command: GPIO.out_w1ts.val = 1UL << Pin_Test2;
without val there is a compilation error. The input command: int Pin_Taster = GPIO.in & (1<<Pin_Taster); does not work.
There is the following message: expected unqualified-id before numeric constant
                                                   #define Pin_Taster 20
                                                   in expansion of macro 'Pin_Taster'
                                                   int Pin_Taster = GPIO.in & (1<<Pin_Taster);
                                                   exit status 1
I use the ESP32_C3 
Many thanks for your answer
Hans

**Comment by maarten-pennings** [comment]
The file `gpio_struct.h` for ESP32, that is, file
```
C:\Users\maarten\AppData\Local\Arduino15\packages\esp32\tools\esp32-arduino-libs\idf-release_v5.1-bd2b9390ef\esp32\include\soc\esp32\include\soc\gpio_struct.h
```

has the following definition of `GPIO`.

```cpp
typedef volatile struct gpio_dev_s {
    uint32_t bt_select;                             /*NA*/
    uint32_t out;                                   /*GPIO0~31 output value*/
    uint32_t out_w1ts;                              /*GPIO0~31 output value write 1 to set*/
    uint32_t out_w1tc;                              /*GPIO0~31 output value write 1 to clear*/
    ... lines omitted ...
    uint32_t in; /*MARK*/                           /*GPIO0~31 input value*/
    union {
        struct {
            uint32_t data:       8;                 /*GPIO32~39 input value*/
            uint32_t reserved8: 24;
        };
        uint32_t val;
    } in1;
    ... lines omitted ...
} gpio_dev_t;
extern gpio_dev_t GPIO;
```

When we look at the C3 entead, that is, file
```
C:\Users\maarten\AppData\Local\Arduino15\packages\esp32\tools\esp32-arduino-libs\idf-release_v5.1-bd2b9390ef\esp32c3\include\soc\esp32c3\include\soc\gpio_struct.h
```

has the following definition of `GPIO`.

```cpp
typedef volatile struct gpio_dev_s {
    uint32_t bt_select;                               /**/
    ... lines omitted ...
    union {
        struct {
            uint32_t data:         26;
            uint32_t reserved26:    6;
        };
        uint32_t val;
    } out;
    union {
        struct {
            uint32_t out_w1ts:  26;
            uint32_t reserved26: 6;
        };
        uint32_t val;
    } out_w1ts;
    union {
        struct {
            uint32_t out_w1tc:  26;
            uint32_t reserved26: 6;
        };
        uint32_t val;
    } out_w1tc;
    ... lines omitted ...
    union {
        struct {
            uint32_t data:        26;
            uint32_t reserved26:   6;
        };
        uint32_t val;
    } in; /*MARK*/
    ... lines omitted ...
} gpio_dev_t;
extern gpio_dev_t GPIO;
```

In both files I have added `/*MARK*/` for the definition of `in`.

We see that for the ESP, `in` is just an `uint32_t`, so we can use `in` as an integer like so `int but = GPIO.in & (1<<BUT)`.

We see that for ESP32C3, `in` is a union

```cpp
    union {
        struct {
            uint32_t data:        26;
            uint32_t reserved26:   6;
        };
        uint32_t val;
    } in; /*MARK*/
```

and it has a field `val` that maps to an `uint32_t`.

So you probably have to use `int but = GPIO.in.val & (1<<BUT)`.

**Comment by Bastler100** [comment]
Hello Maarten,
many thanks for your answer.
Hans

**Comment by maarten-pennings** [comment]
Good luck with your project.
I took the freedom to close the issue.
